# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ed604eacd253ec71743354f2635b4fea4190d202d496b842d9e7955d851159ae9d14d2f79538ee90f944ea8b852d611fa25941ec562680fe242f386f7d585ed8

test:
  secret_key_base: e52dc95bec4a64b060174a5da4b0a88461be5df1c522035dbf1918a63e92a32722cc218361f90ead5e80b439cbad57b89e3e21f1fd52107968f4f3ff75953d8f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
